server:
  port: 9000
  tomcat.max-threads: 300

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sakila?useSSL=true&useUnicode=yes&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: root

  redis:
    host: 127.0.0.1
    port: 6379
    database: 1