server:
  port: 9000
  tomcat.max-threads: 300

spring:
  profiles:
    active: @myActivateFile@,common-@myActivateFile@,mq-@myActivateFile@,redis-@myActivateFile@
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 30
      auto-commit: true
      idle-timeout: 1200000
      max-lifetime: 1800000
      connection-timeout: 60000
      connection-test-query: SELECT 1
  redis:
    serializer: jackson
    timeout: 5000
    commandTimeout: 5000
    jedis:
      pool:
        max-active: 200
        min-idle: 0
        max-idle: 5
        max-wait: -1

thread:
  pool:
    corePoolSize: 50
    maxPoolSize: 100
    queueSize: 30
    keepAlive: 60
