server:
  port: 9001
  tomcat.max-threads: 300

spring:
  profiles:
    active: @myActivateFile@,common-@myActivateFile@,mq-@myActivateFile@,redis-@myActivateFile@
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    idleTimeout: 260000
    maxLifetime: 275000
    connectionTimeout: 60000
    minIdle: 20
    maximumPoolSize: 100
    connectionTestQuery: SELECT 1
    poolName: HikariPool
    cachePrepStmts: true
    prepStmtCacheSize: 300
    prepStmtCacheSqlLimit: 2048
  redis:
    serializer: jackson
    timeout: 5000
    commandTimeout: 5000
    jedis:
      pool:
        max-active: 200
        min-idle: 0
        max-idle: 5
        max-wait: -1

thread:
  pool:
    corePoolSize: 50
    maxPoolSize: 100
    queueSize: 30
    keepAlive: 60
